from __future__ import annotations

import json
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

import numpy as np


class Exporter(ABC):
    """Base class for trajectory exporters."""

    def __init__(self, output_dir: str | Path) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    @abstractmethod
    def export(
        self,
        trajectory: dict[str, Any],
        filename: str,
        metadata: dict[str, Any] | None = None,
    ) -> Path:
        """Export a trajectory to disk."""
        ...


class JSONExporter(Exporter):
    """Export trajectories as JSON."""

    def export(
        self,
        trajectory: dict[str, Any],
        filename: str,
        metadata: dict[str, Any] | None = None,
    ) -> Path:
        out_path = self.output_dir / (filename + ".json")
        payload: dict[str, Any] = {"metadata": metadata or {}}

        for key, value in trajectory.items():
            if isinstance(value, np.ndarray):
                payload[key] = value.tolist()
            elif hasattr(value, "__len__") and not isinstance(value, (str, bytes)):
                payload[key] = list(value)
            else:
                payload[key] = value

        out_path.write_text(json.dumps(payload, indent=2))
        return out_path


class ROS2Exporter(Exporter):
    """Export trajectories to ROS2-compatible CSV + YAML."""

    def __init__(
        self,
        output_dir: str | Path,
        joint_names: list[str] | None = None,
        frame_id: str = "base_link",
    ) -> None:
        super().__init__(output_dir)
        self.joint_names = list(joint_names) if joint_names else []
        self.frame_id = frame_id

    def export(
        self,
        trajectory: dict[str, Any],
        filename: str,
        metadata: dict[str, Any] | None = None,
    ) -> Path:
        states = self._extract_states(trajectory)
        timestamps = self._extract_timestamps(trajectory, len(states))
        csv_path = self._write_csv(filename, timestamps, states)
        return self._write_yaml(filename, csv_path, metadata)

    def _extract_states(self, trajectory: dict[str, Any]) -> np.ndarray:
        for key in ("states", "actions", "observations", "state"):
            if key in trajectory:
                value = trajectory[key]
                return value if isinstance(value, np.ndarray) else np.asarray(value)
        raise ValueError("Trajectory must contain one of: states, actions, observations, state")

    def _extract_timestamps(self, trajectory: dict[str, Any], num_frames: int) -> np.ndarray:
        if "timestamps" in trajectory:
            ts = trajectory["timestamps"]
            return ts if isinstance(ts, np.ndarray) else np.asarray(ts)
        return np.arange(num_frames) / 30.0

    def _write_csv(self, filename: str, timestamps: np.ndarray, states: np.ndarray) -> Path:
        csv_path = self.output_dir / (filename + "_trajectory.csv")
        header = ["time_sec"]
        if self.joint_names and len(self.joint_names) == states.shape[-1]:
            header.extend(self.joint_names)
        else:
            header.extend("joint_" + str(i) for i in range(states.shape[-1]))

        rows = np.column_stack([timestamps, states.reshape(len(timestamps), -1)])
        np.savetxt(csv_path, rows, delimiter=",", header=",".join(header), comments="")
        return csv_path

    def _write_yaml(self, filename: str, csv_path: Path, metadata: dict[str, Any] | None) -> Path:
        yaml_path = self.output_dir / (filename + "_metadata.yaml")
        payload = {
            "ros__parameters": {
                "trajectory_file": str(csv_path.resolve()),
                "frame_id": self.frame_id,
                "joint_names": self.joint_names,
                "rate_hz": 30.0,
                "metadata": metadata or {},
            }
        }

        lines = ["# ROS2 parameter file generated by SkillPrimitives", ""]
        lines.extend(self._dict_to_yaml(payload))
        yaml_path.write_text("\n".join(lines))
        return yaml_path

    @staticmethod
    def _dict_to_yaml(data: dict[str, Any], indent: int = 0) -> list[str]:
        lines: list[str] = []
        prefix = "  " * indent
        for key, value in data.items():
            if isinstance(value, dict):
                lines.append(prefix + key + ":")
                lines.extend(ROS2Exporter._dict_to_yaml(value, indent + 1))
            elif isinstance(value, list):
                lines.append(prefix + key + ":")
                for item in value:
                    lines.append(prefix + "  - " + str(item))
            elif isinstance(value, str):
                lines.append(prefix + key + ': "' + value + '"')
            else:
                lines.append(prefix + key + ": " + str(value))
        return lines


_EXPORTERS: dict[str, type[Exporter]] = {
    "json": JSONExporter,
    "ros2": ROS2Exporter,
}


def get_exporter(name: str) -> type[Exporter]:
    name = name.lower().strip()
    if name not in _EXPORTERS:
        valid = ", ".join(sorted(_EXPORTERS))
        raise ValueError("Unknown exporter '" + name + "'. Valid: " + valid)
    return _EXPORTERS[name]


def register_exporter(name: str, cls: type[Exporter]) -> None:
    _EXPORTERS[name.lower().strip()] = cls
